name = "Imba"
grammar = "imba"
path_suffixes = ["imba", "imba2"]
line_comments = ["# ", "// "]
block_comment = ["###", "###"]
tab_size = 2
hard_tabs = true
autoclose_before = ";:.,=}])> "
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["comment", "string"] },
]

