
if typeof Imba === 'undefined'
	require './imba'
	require './core.events'
	require './dom'
	require './dom.client'
	require './dom.html'
	require './dom.legacy'
	require './dom.events'
	require './dom.static'
	require './selector'