id = "imba"
name = "Imba"
description = "Imba language support."
version = "0.0.1"
schema_version = 1
authors = ["Imba maintainers"]
repository = "https://github.com/imba/zed-imba"

[language_servers.imba-language-server]
name = "Imba Language Server"
languages = ["Imba"]

[grammars.imba]
repository = "https://github.com/imba/tree-sitter-imba"
rev = "19185dc5137c8fffe356bcada4b5d52cee5922c3"
